import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('meal and creatine checklists persist and edits do not double-count meals', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: /Creatina/ }).click()
  await page.getByRole('button', { name: 'Completar Desayuno', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Marcar Desayuno como pendiente' })).toBeVisible()
  await expect(page.locator('.metric-card').filter({ hasText: 'Registrado' })).toContainText('983')
  await page.screenshot({ path: info.outputPath('checklist.png'), fullPage: true })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Marcar Desayuno como pendiente' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Creatina/ })).toContainText('Hecho')
  await page.getByRole('button', { name: 'Marcar Desayuno como pendiente' }).click()
  await page.getByRole('button', { name: 'Completar Desayuno', exact: true }).click()
  await expect(page.locator('.metric-card').filter({ hasText: 'Registrado' })).toContainText('983')
  await page.getByRole('button', { name: 'Plan', exact: true }).click()
  await page.getByRole('button', { name: 'Editar Desayuno', exact: true }).click()
  await page.getByLabel('Comida', { exact: true }).fill('Desayuno editado')
  await page.screenshot({ path: info.outputPath('editor.png'), fullPage: true })
  await page.getByRole('button', { name: 'Hoy', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Desayuno editado' })).toBeVisible()
  expect(errors).toEqual([])
})

test('shared appearance, contrast, responsive layout and logo rendering', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Desayuno', exact: true })).toBeVisible()
  for (const theme of ['dark', 'light']) {
    await page.emulateMedia({ colorScheme: theme as 'dark' | 'light' })
    await expect(page.locator('html')).toHaveAttribute('data-theme-mode', 'system')
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    await page.getByRole('button', { name: 'Cambiar acento', exact: true }).click()
    await page.getByRole('menuitemradio', { name: 'Color Azul' }).click()
    await expect(page.locator('html')).toHaveAttribute('data-accent', 'blue')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.brand-mark img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth === 192)).toBe(true)
    const findings = await new AxeBuilder({ page }).disableRules(['meta-viewport']).analyze()
    expect(findings.violations.filter((issue) => ['serious', 'critical'].includes(issue.impact ?? ''))).toEqual([])
    await page.screenshot({ path: info.outputPath(`home-${theme}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Elegir tema' }).click()
  await page.getByRole('menuitemradio', { name: 'Oscuro', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Elegir tema' }).click()
  await page.getByRole('menuitemradio', { name: 'Dispositivo', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('meta[name="theme-color"]')).toHaveAttribute('content', '#0d0f12')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme-mode', 'system')
})
